services:
  - type: web
    name: eventsphere
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://eventsphere.onrender.com
